version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "12:00"
      timezone: Asia/Shanghai
    target-branch: develop
    commit-message:
      prefix: "⬆️ Chore(deps)"
      prefix-development: "⬆️ Chore(dev-deps)"
      include: "scope"
  - package-ecosystem: npm
    directory: "/"
    reviewers:
      - "@yuba-technology/backend-team"
    labels:
      - dependencies
      - backend
    schedule:
      interval: weekly
      day: friday
      time: "12:00"
      timezone: Asia/Shanghai
    versioning-strategy: increase
    rebase-strategy: disabled
    target-branch: develop
    commit-message:
      prefix: "⬆️ Chore(deps)"
      prefix-development: "⬆️ Chore(dev-deps)"
      include: "scope"
